### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by smolbun** [muhiris/wgpt#1]
I tried the examples provided but seem to be getting this error.
`Error: Unexpected token < in JSON at position 0`

npm version is 7.5.2

**Comment by muhiris** [comment]
It looks like they closed down https://chatbot.theb.ai/ and moved to https://beta.theb.ai/

**Comment by muhiris** [comment]
Thank you for highlighting this issue.  I have successfully created a scraper in Node.js, which functions well but a bit slow. 

To run the scraper, you first uninstall the package and then install the package:
```
npm uninstall wgpt
```
then 
```
npm i -g wgpt 
```
or
```
wgpt i -g wgpt@1.0.8
```
