### ISSUE TITLE
The bot doesn't anwser the question

### ISSUE THREAD

**Issue by victor03303** [muhiris/wgpt#2]
Dear Muhiris

Thank you for sharing your application with us!

However when I try to use it, I get the same welcome message as if the bot isn't aware of my question.
![image](https://github.com/muhiris/wgpt/assets/55033363/3d5da21d-374f-45d0-b7bb-39eddbdd9ebd)

**Comment by muhiris** [comment]
Chromium is being launched, and the input tag is being accessed, but it seems that your input is not being sent. I'm curious, was wgpt functioning properly before, or has it never worked? It appears to be functioning flawlessly on my side.

![image](https://github.com/muhiris/wgpt/assets/80543033/b62115b5-4901-4771-b254-e9fc85a6bbe3)

**Comment by muhiris** [comment]
It's updated. Now It's response is very fast and quick.

You can try `npm uninstall wgpt` and then install again using `npm install wgpt@1.1.1`
